name: ez-finance
dependencies:
- cycler=0.10.0=py35_0
- flask=0.10.1=py35_1
- flask-wtf=0.11=py35_0
- freetype=2.5.5=0
- itsdangerous=0.24=py35_0
- jinja2=2.8=py35_0
- libpng=1.6.17=0
- mako=1.0.3=py35_0
- markupsafe=0.23=py35_0
- matplotlib=1.5.1=np110py35_0
- mkl=11.3.1=0
- numpy=1.10.4=py35_0
- openssl=1.0.2g=0
- pandas=0.17.1=np110py35_0
- pip=8.0.3=py35_0
- pyparsing=2.0.3=py35_0
- pyqt=4.11.4=py35_1
- python=3.5.1=0
- python-dateutil=2.4.2=py35_0
- pytz=2015.7=py35_0
- qt=4.8.7=1
- readline=6.2=2
- scipy=0.17.0=np110py35_0
- seaborn=0.7.0=py35_0
- setuptools=20.1.1=py35_0
- sip=4.16.9=py35_0
- six=1.10.0=py35_0
- sqlalchemy=1.0.12=py35_0
- sqlite=3.9.2=0
- tk=8.5.18=0
- werkzeug=0.11.4=py35_0
- wheel=0.29.0=py35_0
- wtforms=2.0.2=py35_0
- xz=5.0.5=1
- zlib=1.2.8=0
- pip:
  - alembic==0.8.4
  - flask-migrate==1.8.0
  - flask-script==2.0.5
  - flask-sqlalchemy==2.1
  - flask-testing==0.4.2
  - python-editor==0.5

