"""empty message

Revision ID: 28c5945d624
Revises: 170ec599e68
Create Date: 2015-11-27 10:42:38.719113

"""

# revision identifiers, used by Alembic.
revision = '28c5945d624'
down_revision = '170ec599e68'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('owner', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'owner')
    ### end Alembic commands ###
