"""empty message

Revision ID: 3189645e1bc
Revises: 49063f6592f
Create Date: 2015-12-05 13:41:12.029986

"""

# revision identifiers, used by Alembic.
revision = '3189645e1bc'
down_revision = '49063f6592f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('retirement', sa.Integer()))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'retirement')
    ### end Alembic commands ###
