"""empty message

Revision ID: 49063f6592f
Revises: 28c5945d624
Create Date: 2015-11-29 18:30:43.352493

"""

# revision identifiers, used by Alembic.
revision = '49063f6592f'
down_revision = '28c5945d624'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account_history')
    ### end Alembic commands ###
